AWSTemplateFormatVersion: "2010-09-09"
Description: IAM roles used by infra-base for codebuild

Parameters:
  BucketInfra:
    Type: String

Resources:

  RoleCodeBuildInfra:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: code-build-infra
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: S3GetBuildsInfraBase
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub arn:aws:s3:::${BucketInfra}/infra-base/*
        - PolicyName: S3PublishTemplatesInfraBase
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectTagging
                  - s3:PutObjectVersionTagging
                  - s3:GetObject*
                  - s3:DeleteObject*
                Resource:
                  - !Sub arn:aws:s3:::${BucketInfra}/cloudformation/infra-base/*
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${BucketInfra}
        - PolicyName: KMSUseAWSS3Key
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt
                  - kms:GenerateDataKey
                  - kms:DescribeKey
                Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
        - PolicyName: LogsCreateBuildStreamInfraBase
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/infra-base
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/infra-base:*

  RoleCodeBuildWebAnalytics:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: code-build-web-analytics
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: S3GetBuildsWebAnalytics
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub arn:aws:s3:::${BucketInfra}/web-analytics/*
        - PolicyName: S3PublishTemplatesWebAnalytics
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectTagging
                  - s3:PutObjectVersionTagging
                  - s3:GetObject*
                  - s3:DeleteObject*
                Resource:
                  - !Sub arn:aws:s3:::${BucketInfra}/cloudformation/web-analytics/*
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${BucketInfra}
        - PolicyName: KMSUseAWSS3Key
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt
                  - kms:GenerateDataKey
                  - kms:DescribeKey
                Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
        - PolicyName: LogsCreateBuildStreamWebAnalytics
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/web-analytics
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/web-analytics:*
