AWSTemplateFormatVersion: "2010-09-09"
Description: Pipeline for web analytics CI

Parameters:
  Prefix:
    Type: String
  BucketInfra:
    Type: String
  RepoWebAnalyticsName:
    Type: String
  EnvironmentType:
    Type: String

Resources:
  PipelineWebAnalytics:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Location: !Ref BucketInfra
        Type: S3
      Name: web-analytics
      RestartExecutionOnUpdate: True
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/code-pipeline-web-analytics
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName : !Ref RepoWebAnalyticsName
                BranchName : master
              OutputArtifacts:
                - Name: web_analytics_templates
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: web-analytics
              InputArtifacts:
                - Name: web_analytics_templates
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: web_analytics_templates
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: web-analytics
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/cloud-formation-web-analytics
                TemplatePath: web_analytics_templates::web-analytics-top.yml
                ParameterOverrides: !Sub '{"Prefix": "${Prefix}" }'
